### ISSUE TITLE
network type

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/n-instrumentation#29]
https://developer.mozilla.org/en-US/docs/Web/API/Network_Information_API

**Comment by adambraimbridge** [comment]
Super interesting, I vote for tracking this. However it's a bit of a red flag for me. Here's my logic

(a) we want to cohort visits based on connection speed 
(b) so we assume that different network connection types have certain speeds
(c) therefore if we know the network connection type, we know the speed.

I think the error's in part (b). Just because I'm on ADSL doesn't mean I have the same speed as my neighbor, who's also on ADSL. They could be dramatically different if we're connecting to different exchanges. Or the WIFI I might connect to at Starbucks or the tube will have a dramatically different speed to the WIFI I have at home. 

If we want to do the speed-cohorting thing, we should ignore network connection type and measure connection speed directly. How can we do that? I have no idea. Could we measure the download speed of something that is guaranteed to load after the CTM javascript loads?

**Comment by ironsidevsquincy** [comment]
FYI, already tracking this

https://github.com/Financial-Times/n-third-party-code/pull/36

**Comment by wheresrhys** [comment]
nice one
